# -------------------------------------------------------------------------------
# cov.yaml (Coverage Testing workflow)
#
# A GitHub Actions workflow for running generating a coverage report 
# comment on pull requests.
#
# Resources:
# > MishaKav on GitHub, "GitHub Action: pytest coverage comment", https://github.com/MishaKav/pytest-coverage-comment/
# > pytest docs, https://docs.pytest.org/en/7.2.x/how-to/output.html
# -----------------------------------------------------------------------------
name: Coverage Report

# Controls when the workflow will run
on:
  # Activate workflow on pull requests
  pull_request:

  # allows you to manually execute this pipeline from the Actions tab.
  workflow_dispatch:

# set the default working directory to be the code space	
defaults:
  run:
    working-directory: ./Code

jobs:
  build:
    name: Coverage Report
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-Python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Build Coverage report
        run: |
          pytest --cov-report "xml:tests\coverage.xml" --cov=src tests/

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: tests\coverage.xml