name: JS CI
on: push

# set the default working directory to be the code space	
defaults:
  run:
    working-directory: ./Code

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install jest
    - name: Run tests
      run: npm test